(() => {
"use strict";
const cfg=window.RIFA_CONFIG,db=window.supabaseClient,SESSION_KEY="junior_rifa_admin_session_v1";
const state={token:localStorage.getItem(SESSION_KEY)||"",dashboard:null,channel:null,confirmResolver:null,deferredInstallPrompt:null,photo:{path:null,url:null,selectedFile:null,previewObjectUrl:null,busy:false}};
const $=id=>document.getElementById(id);const el={loginCard:$("loginCard"),loginForm:$("adminLoginForm"),email:$("adminEmail"),password:$("adminPassword"),setupWarning:$("adminSetupWarning"),panel:$("adminPanel"),refresh:$("refreshAdminBtn"),logout:$("logoutBtn"),install:$("installAdminBtn"),totalNumbers:$("statTotalNumbers"),available:$("statAvailable"),pending:$("statPending"),paid:$("statPaid"),buyers:$("statBuyers"),potential:$("statPotential"),raffleRaised:$("statRaffleRaised"),donations:$("statDonations"),grandTotal:$("statGrandTotal"),goalRemaining:$("statGoalRemaining"),goalPercent:$("statGoalPercent"),goalPercentBig:$("goalPercentBig"),goalBar:$("goalBar"),goalText:$("goalText"),goalTitle:$("goalTitle"),quantityForm:$("quantityForm"),quantityInput:$("quantityInput"),quantityRange:$("quantityRange"),quantityUnitPrice:$("quantityUnitPrice"),quantityPotential:$("quantityPotential"),manualForm:$("manualForm"),manualName:$("manualName"),manualWhatsapp:$("manualWhatsapp"),manualNumbers:$("manualNumbers"),manualStatus:$("manualStatus"),donationForm:$("donationForm"),donationAmount:$("donationAmount"),donationNote:$("donationNote"),donationList:$("donationList"),toggleSales:$("toggleSalesBtn"),salesStatus:$("salesStatusText"),availableSummaryCount:$("availableSummaryCount"),availableNumbers:$("availableNumbers"),numberGrid:$("adminNumberGrid"),mapSummaryTitle:$("mapSummaryTitle"),search:$("buyerSearch"),filter:$("buyerFilter"),buyerCards:$("buyerCards"),exportCsv:$("exportCsvBtn"),simulate:$("simulateDrawBtn"),simulation:$("simulationResult"),drawStatus:$("drawStatusText"),drawRange:$("drawRangeText"),drawConfirm:$("drawConfirmInput"),officialDraw:$("officialDrawBtn"),winner:$("winnerAdmin"),confirmModal:$("confirmModal"),confirmTitle:$("confirmTitle"),confirmMessage:$("confirmMessage"),confirmDetails:$("confirmDetails"),confirmIcon:$("confirmIcon"),confirmPinWrap:$("confirmPinWrap"),confirmPin:$("confirmPin"),confirmPinError:$("confirmPinError"),confirmCancel:$("confirmCancelBtn"),confirmOk:$("confirmOkBtn"),editModal:$("editModal"),editForm:$("editForm"),editId:$("editReservationId"),editName:$("editName"),editWhatsapp:$("editWhatsapp"),editCancel:$("editCancelBtn"),photoState:$("photoAdminState"),photoCurrent:$("currentBeneficiaryPhoto"),photoCurrentInfo:$("currentBeneficiaryPhotoInfo"),photoInput:$("beneficiaryPhotoInput"),photoNewWrap:$("newBeneficiaryPhotoPreviewWrap"),photoNew:$("newBeneficiaryPhotoPreview"),photoNewInfo:$("newBeneficiaryPhotoInfo"),photoSave:$("saveBeneficiaryPhotoBtn"),photoRemove:$("removeBeneficiaryPhotoBtn"),photoProgress:$("beneficiaryPhotoProgress"),photoMessage:$("beneficiaryPhotoMessage"),toast:$("adminToast")};
const DDDS=new Set("11 12 13 14 15 16 17 18 19 21 22 24 27 28 31 32 33 34 35 37 38 41 42 43 44 45 46 47 48 49 51 53 54 55 61 62 63 64 65 66 67 68 69 71 73 74 75 77 79 81 82 83 84 85 86 87 88 89 91 92 93 94 95 96 97 98 99".split(" "));
const money=c=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format((Number(c)||0)/100),digits=v=>String(v||"").replace(/\D/g,"");
const raffleState=()=>state.dashboard?.state||{};const totalNumbers=()=>Math.max(1,Number(raffleState().total_numbers||cfg.fallbackTotalNumbers||1000));const unitPrice=()=>Math.max(1,Number(raffleState().unit_price_cents||cfg.fallbackUnitPriceCents||1000));const goalCents=()=>Math.max(1,Number(raffleState().goal_cents||cfg.fallbackGoalCents||1000000));const numberDigits=()=>String(totalNumbers()).length;const pad=n=>String(n).padStart(numberDigits(),"0");
function normalizePhone(v,{mobile=true}={}){let d=digits(v);if(d.startsWith("00"))d=d.slice(2);if(d.startsWith("5555")&&(d.length===14||d.length===15))d=d.slice(2);if(d.startsWith("55")&&(d.length===12||d.length===13))d=d.slice(2);if(d.length!==10&&d.length!==11)return{ok:false,error:"Telefone inválido."};if(!DDDS.has(d.slice(0,2)))return{ok:false,error:"DDD inválido."};if(d.length===11&&d[2]!=="9")return{ok:false,error:"Celular inválido."};if(mobile&&d.length!==11)return{ok:false,error:"Informe um celular com DDD."};return{ok:true,national:d,e164:`55${d}`}}
function fmtPhone(v){const p=normalizePhone(v,{mobile:false});if(!p.ok)return String(v||"");const d=p.national;return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`}
function toast(m){el.toast.textContent=m;el.toast.classList.add("toast--show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("toast--show"),2800)}
const DEBUG=new URLSearchParams(location.search).get("debug")==="1"||localStorage.getItem("junior_rifa_debug_v1")==="1";
function trace(step,details){if(!DEBUG)return;const stamp=new Date().toISOString();if(details===undefined)console.info(`[RIFA JÚNIOR ${stamp}] ${step}`);else console.info(`[RIFA JÚNIOR ${stamp}] ${step}`,details)}
function errorMessage(e,fallback="Erro desconhecido."){if(typeof e?.message==="string"&&e.message.trim())return e.message.trim();if(typeof e==="string"&&e.trim())return e.trim();return fallback}
function isAdminSessionError(e){const m=errorMessage(e,"").toLowerCase();return /sess[aã]o/.test(m)&&/(inv[aá]lid|expir|ausente|token)/.test(m)}
function showPanel(){el.loginCard.classList.add("hidden");el.panel.classList.remove("hidden")}function showLogin(){el.panel.classList.add("hidden");el.loginCard.classList.remove("hidden")}function clearSession(reason=""){trace("admin.session.clear",reason||undefined);state.token="";localStorage.removeItem(SESSION_KEY)}
async function rpc(name,args={}){trace(`admin.rpc.${name}.start`);const{data,error}=await db.rpc(`junior_${name}_session`,{p_session_token:state.token,...args});if(error){trace(`admin.rpc.${name}.error`,{message:errorMessage(error),code:error?.code||null});throw error}trace(`admin.rpc.${name}.ok`);return data}
const PHOTO_FALLBACK=cfg.beneficiaryPhoto||"assets/junior-foto-placeholder.svg";
function setPhotoMessage(message,kind="normal"){if(!el.photoMessage)return;el.photoMessage.textContent=message;el.photoMessage.classList.remove("photo-message--success","photo-message--error","photo-message--warning");if(kind!=="normal")el.photoMessage.classList.add(`photo-message--${kind}`)}
function setPhotoBusy(busy,text="Enviando foto…"){state.photo.busy=!!busy;if(el.photoProgress){el.photoProgress.classList.toggle("hidden",!busy);const strong=el.photoProgress.querySelector("strong");if(strong)strong.textContent=text}if(el.photoInput)el.photoInput.disabled=busy;if(el.photoSave)el.photoSave.disabled=busy||!state.photo.selectedFile;if(el.photoRemove)el.photoRemove.disabled=busy||!state.photo.path}
function clearPhotoPreview(){if(state.photo.previewObjectUrl){URL.revokeObjectURL(state.photo.previewObjectUrl);state.photo.previewObjectUrl=null}state.photo.selectedFile=null;if(el.photoInput)el.photoInput.value="";if(el.photoNew){el.photoNew.removeAttribute("src")}if(el.photoNewWrap)el.photoNewWrap.classList.add("hidden");if(el.photoSave)el.photoSave.disabled=true}
function renderPhotoStatus(data={}){state.photo.path=data.path||null;state.photo.url=data.url||null;if(el.photoCurrent){el.photoCurrent.onerror=()=>{el.photoCurrent.onerror=null;el.photoCurrent.src=PHOTO_FALLBACK};el.photoCurrent.src=state.photo.url||PHOTO_FALLBACK}if(el.photoCurrentInfo)el.photoCurrentInfo.textContent=state.photo.path?`Ativa no Supabase: ${state.photo.path}`:"Nenhuma foto enviada pelo Admin. O site usa o placeholder.";if(el.photoState)el.photoState.textContent=state.photo.path?"Foto ativa":"Placeholder";if(el.photoRemove)el.photoRemove.disabled=state.photo.busy||!state.photo.path}
async function mediaGateway(action,{file=null}={}){if(!cfg.adminMedia?.gatewayUrl)throw new Error("A Edge Function da foto ainda não foi configurada.");trace(`admin.media.${action}.start`);let body,headers={};if(file){const form=new FormData();form.append("action",action);form.append("session_token",state.token);form.append("file",file,file.name);body=form}else{headers["Content-Type"]="application/json";body=JSON.stringify({action,session_token:state.token})}let response;try{response=await fetch(cfg.adminMedia.gatewayUrl,{method:"POST",headers,body})}catch(e){trace(`admin.media.${action}.network_error`,errorMessage(e));throw new Error("Não foi possível acessar a Edge Function junior-admin-media.")}const data=await response.json().catch(()=>({}));if(response.status===401){const err=new Error(data.message||"A área da foto não conseguiu validar a sessão do Admin.");err.code="MEDIA_SESSION_401";trace(`admin.media.${action}.unauthorized`,errorMessage(err));throw err}if(!response.ok||data.success===false){const err=new Error(data.message||`Falha na área da foto (HTTP ${response.status}).`);err.code=`MEDIA_HTTP_${response.status}`;trace(`admin.media.${action}.error`,{status:response.status,message:errorMessage(err),details:data?.details||null});throw err}trace(`admin.media.${action}.ok`);return data}
async function loadPhotoStatus(){if(!state.token||!el.photoCurrent)return;try{const data=await mediaGateway("status");renderPhotoStatus(data);setPhotoMessage("JPG, JPEG, PNG ou WEBP • máximo de 8 MB.");return true}catch(e){renderPhotoStatus({});const m=errorMessage(e,"Não foi possível consultar a foto.");if(e?.code==="MEDIA_SESSION_401")setPhotoMessage(`${m} O painel continua conectado; verifique o SQL/Edge Function da foto.`,"warning");else setPhotoMessage(/404|Function|Edge|configurad|Failed to fetch|acessar/i.test(m)?"A foto está temporariamente indisponível. Confira a Edge Function junior-admin-media e o SQL oficial. O restante do Admin continua funcionando.":m,"warning");trace("admin.media.status.nonfatal",m);return false}}
function validatePhotoFile(file){if(!file)throw new Error("Escolha uma foto primeiro.");const allowed=new Set(cfg.adminMedia?.allowedMimeTypes||["image/jpeg","image/png","image/webp"]),max=Number(cfg.adminMedia?.maxFileBytes||8388608);if(!allowed.has(file.type))throw new Error("Formato inválido. Use JPG, JPEG, PNG ou WEBP.");if(file.size<=0)throw new Error("O arquivo da foto está vazio.");if(file.size>max)throw new Error(`A foto excede o limite de ${(max/1024/1024).toFixed(0)} MB.`);return true}
function choosePhoto(){try{const file=el.photoInput?.files?.[0];validatePhotoFile(file);clearPhotoPreview();state.photo.selectedFile=file;state.photo.previewObjectUrl=URL.createObjectURL(file);el.photoNew.src=state.photo.previewObjectUrl;el.photoNewWrap.classList.remove("hidden");el.photoNewInfo.textContent=`${file.name} • ${(file.size/1024/1024).toFixed(2).replace(".",",")} MB`;el.photoSave.disabled=false;setPhotoMessage("Confira a prévia. A foto só muda no site depois de clicar em Salvar nova foto.")}catch(e){clearPhotoPreview();setPhotoMessage(e.message||"Arquivo inválido.","error");toast(e.message||"Arquivo inválido.")}}
async function savePhoto(){if(state.photo.busy)return;try{const file=state.photo.selectedFile;validatePhotoFile(file);const ok=await openConfirm({title:"Salvar nova foto do Júnior?",message:"A nova foto substituirá a foto atual no site público.",details:"A arte da prévia do WhatsApp não será alterada.",icon:"📷"});if(!ok)return;setPhotoBusy(true,"Enviando e salvando foto…");setPhotoMessage("Enviando a foto com segurança…");const data=await mediaGateway("upload",{file});renderPhotoStatus(data);clearPhotoPreview();setPhotoMessage("Foto salva. O site público já apontará para a nova URL, sem reutilizar o arquivo anterior.","success");toast("Foto do Júnior atualizada.")}catch(e){setPhotoMessage(e.message||"Falha ao salvar a foto.","error");toast(e.message||"Falha ao salvar a foto.")}finally{setPhotoBusy(false)}}
async function removePhoto(){if(state.photo.busy||!state.photo.path)return;try{const ok=await openConfirm({title:"Remover foto atual do Júnior?",message:"Deseja realmente remover a foto atual do Júnior?",details:"O site público voltará a mostrar o placeholder. A arte do WhatsApp continuará igual.",icon:"🗑"});if(!ok)return;setPhotoBusy(true,"Removendo foto…");const data=await mediaGateway("remove");renderPhotoStatus(data);clearPhotoPreview();setPhotoMessage("Foto removida. O site público voltou a usar o placeholder.","success");toast("Foto removida.")}catch(e){setPhotoMessage(e.message||"Falha ao remover a foto.","error");toast(e.message||"Falha ao remover a foto.")}finally{setPhotoBusy(false)}}

function showLoginError(message){if(!el.setupWarning)return;el.setupWarning.textContent=message;el.setupWarning.classList.remove("hidden")}
function clearLoginError(){if(!el.setupWarning)return;el.setupWarning.classList.add("hidden")}
async function login(ev){ev.preventDefault();clearLoginError();trace("admin.login.start",{email:el.email.value.trim().toLowerCase()});try{const{data,error}=await db.rpc("junior_admin_login_session",{p_email:el.email.value.trim().toLowerCase(),p_password:el.password.value});if(error)throw error;if(!data?.session_token)throw new Error("Login não autorizado.");state.token=data.session_token;localStorage.setItem(SESSION_KEY,state.token);el.password.value="";trace("admin.login.rpc_ok.token_saved");const ok=await refresh({throwOnError:true,source:"login"});if(ok){subscribe();trace("admin.login.panel_ready")}}catch(e){const m=errorMessage(e,"Login inválido.");trace("admin.login.error",m);if(!state.dashboard||isAdminSessionError(e))clearSession("falha no login/dashboard");showLogin();showLoginError(state.token?`A senha foi aceita, mas o painel não conseguiu carregar: ${m}`:m);toast(state.token?"Senha aceita, mas o painel apresentou erro.":m)}}
async function logout(){const t=state.token;trace("admin.logout.start");clearSession("logout manual");try{if(t)await db.rpc("junior_admin_logout_session",{p_session_token:t})}catch(e){trace("admin.logout.rpc_error",errorMessage(e))}showLogin()}
async function refresh({throwOnError=false,source="refresh"}={}){trace(`admin.refresh.${source}.start`);let dashboard;try{dashboard=await rpc("admin_dashboard")}catch(e){const m=errorMessage(e,"Falha ao carregar o painel.");trace(`admin.refresh.${source}.dashboard_error`,m);if(isAdminSessionError(e)){clearSession("dashboard informou sessão inválida");showLogin()}else{showLoginError(`Falha ao carregar o painel: ${m}`)}if(throwOnError)throw e;toast(m);return false}state.dashboard=dashboard;render();showPanel();clearLoginError();trace(`admin.refresh.${source}.dashboard_ok`);loadPhotoStatus().catch(e=>trace("admin.media.status.unhandled",errorMessage(e)));return true}
function raised(){return(state.dashboard?.reservations||[]).filter(r=>r.payment_status==="paid").reduce((s,r)=>s+Number(r.expected_amount_cents||0),0)}
function render(){const d=state.dashboard,s=d.stats||{},r=raised(),don=Number(s.donation_total_cents||0),total=r+don,goal=goalCents(),remaining=Math.max(0,goal-total),pct=Math.min(100,total/goal*100),qty=totalNumbers(),potential=qty*unitPrice(),range=`${String(1).padStart(numberDigits(),"0")} a ${String(qty).padStart(numberDigits(),"0")}`;el.totalNumbers.textContent=qty.toLocaleString("pt-BR");el.available.textContent=s.available||0;el.pending.textContent=s.pending||0;el.paid.textContent=s.paid||0;el.buyers.textContent=s.buyers||0;el.potential.textContent=money(potential);el.raffleRaised.textContent=money(r);el.donations.textContent=money(don);el.grandTotal.textContent=money(total);el.goalRemaining.textContent=money(remaining);el.goalPercent.textContent=`${pct.toFixed(1).replace(".",",")}% alcançado`;el.goalPercentBig.textContent=`${pct.toFixed(1).replace(".",",")}%`;el.goalBar.style.width=`${pct}%`;el.goalTitle.textContent=money(goal);el.goalText.textContent=`${money(total)} arrecadados • faltam ${money(remaining)}.`;el.quantityInput.value=qty;el.quantityRange.textContent=range;el.quantityUnitPrice.textContent=money(unitPrice());el.quantityPotential.textContent=money(potential);el.manualNumbers.placeholder=`Ex.: ${pad(1)}, ${pad(Math.min(2,qty))}, ${pad(Math.min(qty,150))}`;el.mapSummaryTitle.textContent=`Mapa dos ${qty.toLocaleString("pt-BR")} números`;el.drawRange.textContent=`Faixa atual: ${range}. O sorteio considera somente números pagos.`;renderDonations();renderSales();renderNumbers();renderBuyers();renderDraw()}
function renderDonations(){const rows=state.dashboard?.donations||[];el.donationList.innerHTML=rows.length?rows.map(x=>`<div class="donation-item"><div><strong>${money(x.amount_cents)}</strong><small>${x.note?escapeHtml(x.note)+" • ":""}${new Date(x.created_at).toLocaleString("pt-BR")}</small></div><button class="button button--danger" data-del-donation="${x.id}">Excluir</button></div>`).join(""):"<p class='muted'>Nenhuma doação cadastrada.</p>";document.querySelectorAll("[data-del-donation]").forEach(b=>b.onclick=()=>deleteDonation(b.dataset.delDonation))}
function renderSales(){const closed=!!state.dashboard?.state?.sales_closed;el.toggleSales.textContent=closed?"Reabrir vendas":"Fechar vendas";el.salesStatus.textContent=closed?"As vendas estão fechadas.":"As vendas estão abertas."}
function renderNumbers(){const qty=totalNumbers(),nums=(state.dashboard?.numbers||[]).filter(n=>Number(n.number)<=qty),available=nums.filter(n=>n.status==="available");el.availableSummaryCount.textContent=available.length;el.availableNumbers.innerHTML=available.map(n=>`<span>${pad(n.number)}</span>`).join("");el.numberGrid.innerHTML=nums.map(n=>`<span class="${n.status==="paid"?"num--paid":n.status==="pending"?"num--pending":""}" title="${n.status}">${pad(n.number)}</span>`).join("")}
function filtered(){const q=el.search.value.trim().toLowerCase(),f=el.filter.value;return(state.dashboard?.reservations||[]).filter(r=>{const hay=`${r.buyer_name} ${r.whatsapp} ${(r.numbers||[]).map(pad).join(" ")}`.toLowerCase();if(q&&!hay.includes(q))return false;if(f==="whatsapp")return r.payment_status==="paid"&&!r.confirmation_whatsapp_sent_at;if(f!=="all"&&r.payment_status!==f)return false;return true})}
function statusLabel(s){return s==="paid"?"Pago":s==="pending"?"Pendente":s==="expired"?"Expirado":"Cancelado"}function providerLabel(p){return p==="personal_pix"?"Pix pessoal":p==="cash"?"Dinheiro":p==="manual"?"Manual":"InfinitePay"}
function renderBuyers(){const rows=filtered();el.buyerCards.innerHTML=rows.length?rows.map(r=>{const p=normalizePhone(r.whatsapp),waOk=p.ok;return`<article class="buyer-card"><div class="buyer-card__top"><div><h3>${escapeHtml(r.buyer_name)}</h3><small>${escapeHtml(fmtPhone(r.whatsapp))}</small></div><span class="status status--${r.payment_status}">${statusLabel(r.payment_status)}</span></div><div class="buyer-meta"><div><span>Números</span><strong>${(r.numbers||[]).map(pad).join(", ")}</strong></div><div><span>Valor</span><strong>${money(r.expected_amount_cents)}</strong></div><div><span>Pagamento</span><strong>${providerLabel(r.payment_provider)}</strong></div><div><span>Cadastro</span><strong>${new Date(r.created_at).toLocaleDateString("pt-BR")}</strong></div></div>${r.payment_provider==="cash"?`<p class="muted">Dinheiro recebido por: <strong>${escapeHtml(r.cash_received_by||"—")}</strong> • ${escapeHtml(fmtPhone(r.cash_received_phone||""))}</p>`:""}<div class="buyer-actions">${r.payment_status==="paid"?`<button class="button button--warning" data-set-pending="${r.id}">Voltar para pendente</button>`:`<button class="button button--success" data-set-paid="${r.id}">Confirmar pagamento</button>`}<button class="button button--soft" data-edit="${r.id}">Editar</button>${["expired","cancelled"].includes(r.payment_status)?`<button class="button button--soft" data-reactivate="${r.id}">Reativar</button>`:`<button class="button button--danger" data-cancel="${r.id}">Liberar números</button>`}${r.payment_status==="paid"&&!r.confirmation_whatsapp_sent_at&&waOk?`<button class="button whatsapp-action" data-whatsapp="${r.id}">💬 Enviar confirmação</button>`:""}${r.confirmation_whatsapp_sent_at?`<span class="muted">WhatsApp enviado ✓</span>`:""}</div></article>`}).join(""):"<p class='muted'>Nenhum pedido encontrado.</p>";bindBuyerActions()}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function reservation(id){return(state.dashboard?.reservations||[]).find(r=>String(r.id)===String(id))}
function parseNumberList(text){const arr=[...new Set(String(text||"").split(/[\s,;]+/).filter(Boolean).map(x=>Number(x)))];if(!arr.length||arr.some(n=>!Number.isInteger(n)||n<1||n>totalNumbers()))throw new Error(`Use números entre 1 e ${totalNumbers()}.`);return arr.sort((a,b)=>a-b)}
function parseMoney(text){const clean=String(text||"").replace(/[^0-9,.-]/g,"").replace(/\./g,"").replace(",","."),v=Number(clean);if(!Number.isFinite(v)||v<=0)throw new Error("Valor inválido.");return Math.round(v*100)}
function openConfirm({title,message,details="",icon="?",info=false}){return new Promise(res=>{state.confirmResolver=res;el.confirmTitle.textContent=title;el.confirmMessage.textContent=message||"";el.confirmDetails.innerHTML=details;el.confirmDetails.classList.toggle("hidden",!details);el.confirmIcon.textContent=icon;el.confirmPin.value="";el.confirmPinError.classList.add("hidden");el.confirmPinWrap.classList.toggle("hidden",info);el.confirmCancel.classList.toggle("hidden",info);el.confirmOk.textContent=info?"OK":"Confirmar";el.confirmModal.classList.remove("hidden");setTimeout(()=>info?el.confirmOk.focus():el.confirmPin.focus(),20)})}
function closeConfirm(v){el.confirmModal.classList.add("hidden");const r=state.confirmResolver;state.confirmResolver=null;if(r)r(!!v)}async function pinOk(){if(!/^\d{4}$/.test(el.confirmPin.value)){el.confirmPinError.textContent="Digite os 4 números.";el.confirmPinError.classList.remove("hidden");return false}const{data,error}=await db.rpc("junior_admin_verify_action_pin_session",{p_session_token:state.token,p_pin:el.confirmPin.value});if(error||!data?.ok){el.confirmPinError.textContent="Senha incorreta.";el.confirmPinError.classList.remove("hidden");return false}return true}
async function saveQuantity(e){e.preventDefault();const next=Number(el.quantityInput.value),old=totalNumbers();if(!Number.isInteger(next)||next<1)return toast("Informe uma quantidade inteira maior que zero.");if(next===old)return toast("Essa já é a quantidade configurada.");const action=next>old?`aumentar de ${old.toLocaleString("pt-BR")} para ${next.toLocaleString("pt-BR")}`:`reduzir de ${old.toLocaleString("pt-BR")} para ${next.toLocaleString("pt-BR")}`;const ok=await openConfirm({title:"Alterar quantidade da rifa?",message:`Você vai ${action} números.`,details:next<old?"A redução só será aceita se todos os números acima do novo limite estiverem livres. Nenhuma venda ou reserva será apagada.":`Serão criados automaticamente os números adicionais até ${next.toLocaleString("pt-BR")}.`,icon:"#"});if(!ok)return;try{const result=await rpc("admin_set_total_numbers",{p_total_numbers:next});await refresh();toast(`Quantidade atualizada para ${result.total_numbers||next}.`)}catch(err){toast(err.message||"Não foi possível alterar a quantidade.")}}
async function manualCreate(e){e.preventDefault();try{const name=el.manualName.value.trim(),p=normalizePhone(el.manualWhatsapp.value),numbers=parseNumberList(el.manualNumbers.value),paid=el.manualStatus.value==="paid";if(name.length<2)throw new Error("Nome inválido.");if(!p.ok)throw new Error(p.error);const ok=await openConfirm({title:"Cadastrar participante?",message:`${name} • ${numbers.map(pad).join(", ")}`,details:`Status: ${paid?"Pago":"Pendente"}<br>Valor: ${money(numbers.length*unitPrice())}`,icon:"+"});if(!ok)return;await rpc("admin_create_reservation",{p_name:name,p_whatsapp:p.national,p_numbers:numbers,p_paid:paid});el.manualForm.reset();el.manualStatus.value="paid";await refresh();toast("Participante cadastrado.")}catch(e){toast(e.message||"Falha ao cadastrar")}}
async function addDonation(e){e.preventDefault();try{const cents=parseMoney(el.donationAmount.value),note=el.donationNote.value.trim(),ok=await openConfirm({title:"Registrar doação?",message:`Valor: ${money(cents)}`,details:note?escapeHtml(note):"",icon:"❤"});if(!ok)return;await rpc("admin_add_donation",{p_amount_cents:cents,p_note:note||null});el.donationForm.reset();await refresh();toast("Doação registrada.")}catch(e){toast(e.message||"Falha ao registrar doação")}}
async function deleteDonation(id){const d=(state.dashboard?.donations||[]).find(x=>x.id===id);if(!d)return;const ok=await openConfirm({title:"Excluir doação?",message:`Valor: ${money(d.amount_cents)}`,details:"A exclusão altera o total arrecadado.",icon:"!"});if(!ok)return;try{await rpc("admin_delete_donation",{p_donation_id:id});await refresh();toast("Doação excluída.")}catch(e){toast(e.message||"Falha")}}
async function toggleSales(){const closed=!!state.dashboard?.state?.sales_closed,ok=await openConfirm({title:closed?"Reabrir vendas?":"Fechar vendas?",message:closed?"A página voltará a aceitar novas compras.":"Novas compras serão bloqueadas.",icon:"!"});if(!ok)return;try{await rpc("admin_set_sales_closed",{p_closed:!closed});await refresh()}catch(e){toast(e.message||"Falha")}}
async function setPayment(id,paid){const r=reservation(id);if(!r)return;const ok=await openConfirm({title:paid?"Confirmar pagamento?":"Voltar para pendente?",message:r.buyer_name,details:`Números: ${(r.numbers||[]).map(pad).join(", ")}<br>Valor: ${money(r.expected_amount_cents)}`,icon:paid?"✓":"!"});if(!ok)return;try{await rpc("admin_set_payment",{p_reservation_id:r.id,p_paid:paid});await refresh();toast(paid?"Pagamento confirmado.":"Pagamento voltou para pendente.")}catch(e){toast(e.message||"Falha")}}
async function cancelReservation(id){const r=reservation(id);if(!r)return;const ok=await openConfirm({title:"Liberar números?",message:r.buyer_name,details:`Números: ${(r.numbers||[]).map(pad).join(", ")}`,icon:"!"});if(!ok)return;try{await rpc("admin_cancel_reservation",{p_reservation_id:r.id});await refresh();toast("Números liberados.")}catch(e){toast(e.message||"Falha")}}
async function reactivate(id){const r=reservation(id);if(!r)return;const ok=await openConfirm({title:"Reativar pedido?",message:r.buyer_name,details:"Só funciona se todos os números ainda existirem e estiverem livres.",icon:"↻"});if(!ok)return;try{await rpc("admin_reactivate_expired",{p_reservation_id:r.id});await refresh();toast("Pedido reativado.")}catch(e){toast(e.message||"Não foi possível reativar")}}
function openEdit(id){const r=reservation(id);if(!r)return;el.editId.value=r.id;el.editName.value=r.buyer_name;el.editWhatsapp.value=fmtPhone(r.whatsapp);el.editModal.classList.remove("hidden")}
async function saveEdit(e){e.preventDefault();try{const name=el.editName.value.trim(),p=normalizePhone(el.editWhatsapp.value);if(name.length<2)throw new Error("Nome inválido.");if(!p.ok)throw new Error(p.error);const ok=await openConfirm({title:"Salvar alterações?",message:name,details:`WhatsApp: ${fmtPhone(p.national)}`,icon:"✎"});if(!ok)return;await rpc("admin_update_reservation",{p_reservation_id:el.editId.value,p_name:name,p_whatsapp:p.national});el.editModal.classList.add("hidden");await refresh();toast("Comprador atualizado.")}catch(e){toast(e.message||"Falha")}}
async function sendWhatsapp(id){const r=reservation(id),p=normalizePhone(r?.whatsapp);if(!r||!p.ok)return toast("WhatsApp inválido.");const ok=await openConfirm({title:"Enviar confirmação pelo WhatsApp?",message:r.buyer_name,details:`Números: ${(r.numbers||[]).map(pad).join(", ")}`,icon:"💬"});if(!ok)return;try{const x=await rpc("admin_mark_confirmation_whatsapp_sent",{p_reservation_id:r.id});if(x?.already_sent){await refresh();return openConfirm({title:"Mensagem já registrada",message:"Esse comprador já foi marcado como avisado.",icon:"✓",info:true})}const msg=[`Olá, ${r.buyer_name}! ✅`,"",`Seu pagamento da Rifa Beneficente para ajudar na cirurgia do Júnior foi confirmado.`,`🎟️ Seus números: ${(r.numbers||[]).map(pad).join(", ")}`,"","🍀 Boa sorte!","Muito obrigado pela participação. 🙏"].join("\n");await refresh();window.open(`https://wa.me/${p.e164}?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}catch(e){toast(e.message||"Falha ao abrir WhatsApp")}}
function bindBuyerActions(){document.querySelectorAll("[data-set-paid]").forEach(b=>b.onclick=()=>setPayment(b.dataset.setPaid,true));document.querySelectorAll("[data-set-pending]").forEach(b=>b.onclick=()=>setPayment(b.dataset.setPending,false));document.querySelectorAll("[data-cancel]").forEach(b=>b.onclick=()=>cancelReservation(b.dataset.cancel));document.querySelectorAll("[data-reactivate]").forEach(b=>b.onclick=()=>reactivate(b.dataset.reactivate));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));document.querySelectorAll("[data-whatsapp]").forEach(b=>b.onclick=()=>sendWhatsapp(b.dataset.whatsapp))}
function renderDraw(){const st=state.dashboard?.state||{},winner=Number(st.winner_number||0);if(winner){el.drawStatus.textContent="Sorteio oficial realizado.";el.winner.classList.remove("hidden");el.winner.innerHTML=`<strong>${pad(winner)}</strong><span>${escapeHtml(st.winner_name||"")} • ${escapeHtml(fmtPhone(st.winner_whatsapp||""))}</span>`}else{el.winner.classList.add("hidden");el.drawStatus.textContent=st.draw_at?`Sorteio configurado para ${new Date(st.draw_at).toLocaleString("pt-BR")}.`:"A data do sorteio ainda não foi configurada."}el.officialDraw.disabled=el.drawConfirm.value.trim().toUpperCase()!=="SORTEAR"||!!winner}
function paidNumbers(){return(state.dashboard?.numbers||[]).filter(n=>n.status==="paid"&&Number(n.number)<=totalNumbers()).map(n=>Number(n.number))}
function simulateDraw(){const nums=paidNumbers();if(!nums.length)return toast("Não há número pago para testar.");const n=nums[Math.floor(Math.random()*nums.length)];el.simulation.classList.remove("hidden");el.simulation.innerHTML=`Teste: <strong>${pad(n)}</strong><small>Simulação local, não grava resultado.</small>`}
async function officialDraw(){const ok=await openConfirm({title:"Realizar sorteio oficial?",message:"Essa ação é definitiva e usa somente números pagos.",details:`Faixa atual: 1 a ${totalNumbers()} • Pagos elegíveis: ${paidNumbers().length}`,icon:"🎉"});if(!ok)return;try{const x=await rpc("admin_draw_winner");el.drawConfirm.value="";await refresh();toast(`Número sorteado: ${pad(x.number)}`)}catch(e){toast(e.message||"Não foi possível sortear")}}
function exportCsv(){const rows=state.dashboard?.reservations||[],header=["Nome","WhatsApp","Numeros","Status","Pagamento","Valor","Criado","Recebedor dinheiro","Telefone recebedor","WhatsApp enviado"],data=rows.map(r=>[r.buyer_name,r.whatsapp,(r.numbers||[]).map(pad).join(" "),r.payment_status,providerLabel(r.payment_provider),(Number(r.expected_amount_cents||0)/100).toFixed(2),r.created_at,r.cash_received_by||"",r.cash_received_phone||"",r.confirmation_whatsapp_sent_at||""]);const csv=[header,...data].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\r\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="rifa-junior.csv";a.click();URL.revokeObjectURL(a.href)}
function subscribe(){if(state.channel)db.removeChannel(state.channel);state.channel=db.channel("junior-admin-live-v3").on("postgres_changes",{event:"*",schema:"public",table:"junior_raffle_numbers"},()=>refresh({source:"realtime_numbers"})).on("postgres_changes",{event:"*",schema:"public",table:"junior_raffle_public_state"},()=>refresh({source:"realtime_state"})).on("postgres_changes",{event:"*",schema:"public",table:"junior_reservations"},()=>refresh({source:"realtime_reservations"})).subscribe();trace("admin.realtime.subscribed")}
function setupPwa(){if("serviceWorker"in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register("./admin-sw.js").catch(()=>{});window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredInstallPrompt=e;el.install.classList.remove("hidden")});el.install.onclick=async()=>{if(!state.deferredInstallPrompt)return toast("Use o menu do navegador para instalar.");state.deferredInstallPrompt.prompt();await state.deferredInstallPrompt.userChoice;state.deferredInstallPrompt=null;el.install.classList.add("hidden")}}
el.loginForm.addEventListener("submit",login);el.logout.addEventListener("click",logout);el.refresh.addEventListener("click",()=>refresh({source:"manual"}));if(el.photoInput)el.photoInput.addEventListener("change",choosePhoto);if(el.photoSave)el.photoSave.addEventListener("click",savePhoto);if(el.photoRemove)el.photoRemove.addEventListener("click",removePhoto);el.quantityForm.addEventListener("submit",saveQuantity);el.quantityInput.addEventListener("input",()=>{const q=Number(el.quantityInput.value);if(Number.isInteger(q)&&q>0)el.quantityPotential.textContent=money(q*unitPrice())});el.manualForm.addEventListener("submit",manualCreate);el.donationForm.addEventListener("submit",addDonation);el.toggleSales.addEventListener("click",toggleSales);el.search.addEventListener("input",renderBuyers);el.filter.addEventListener("change",renderBuyers);el.exportCsv.addEventListener("click",exportCsv);el.simulate.addEventListener("click",simulateDraw);el.drawConfirm.addEventListener("input",renderDraw);el.officialDraw.addEventListener("click",officialDraw);el.confirmCancel.addEventListener("click",()=>closeConfirm(false));el.confirmModal.querySelector(".modal__backdrop").addEventListener("click",()=>closeConfirm(false));el.confirmOk.addEventListener("click",async()=>{if(el.confirmPinWrap.classList.contains("hidden"))return closeConfirm(true);if(await pinOk())closeConfirm(true)});el.confirmPin.addEventListener("keydown",async e=>{if(e.key==="Enter"){e.preventDefault();if(await pinOk())closeConfirm(true)}});el.editCancel.addEventListener("click",()=>el.editModal.classList.add("hidden"));el.editModal.querySelector(".modal__backdrop").addEventListener("click",()=>el.editModal.classList.add("hidden"));el.editForm.addEventListener("submit",saveEdit);setupPwa();if(state.token){trace("admin.startup.token_found");refresh({source:"startup"}).then(ok=>{if(ok)subscribe()})}else{trace("admin.startup.no_token");showLogin()}
})();