(() => {
  "use strict";
  const cfg=window.RIFA_CONFIG,db=window.supabaseClient,PENDING_KEY="junior_rifa_pagamento_pendente_v1";
  const state={selected:new Set(),numbers:new Map(),raffleState:null,channel:null,pending:loadPending()};
  const $=id=>document.getElementById(id);
  const el={grid:$("numberGrid"),loading:$("loadingNumbers"),available:$("availableCount"),paid:$("paidCount"),pendingCount:$("pendingCount"),progressBar:$("progressBar"),progressText:$("progressText"),selectedNumbers:$("selectedNumbers"),selectedTotal:$("selectedTotal"),selectedNumbersMain:$("selectedNumbersMain"),selectedTotalMain:$("selectedTotalMain"),clear:$("clearSelectionBtn"),openCheckout:$("openCheckoutBtn"),checkoutModal:$("checkoutModal"),checkoutClose:$("checkoutCloseBtn"),cancelChoiceModal:$("cancelChoiceModal"),keepCheckout:$("keepCheckoutBtn"),confirmCancelCheckout:$("confirmCancelCheckoutBtn"),form:$("purchaseForm"),name:$("nameInput"),phone:$("phoneInput"),purchaseButton:$("purchaseButton"),paymentHelp:$("paymentHelp"),badge:$("connectionBadge"),setupWarning:$("setupWarning"),toast:$("toast"),winnerPublic:$("winnerPublic"),winnerPublicNumber:$("winnerPublicNumber"),paymentCard:$("paymentStatusCard"),paymentTitle:$("paymentStatusTitle"),paymentText:$("paymentStatusText"),continuePayment:$("continuePaymentBtn"),receiptLink:$("receiptLink"),methodInfiniteCard:$("methodInfiniteCard"),methodPersonalCard:$("methodPersonalCard"),methodCashCard:$("methodCashCard"),cashPaymentFields:$("cashPaymentFields"),cashReceivedBy:$("cashReceivedByInput"),cashReceivedPhone:$("cashReceivedPhoneInput"),personalPixPanel:$("personalPixPanel"),personalPixKey:$("personalPixKey"),personalPixOwner:$("personalPixOwner"),personalPixAmount:$("personalPixAmount"),personalPixNumbers:$("personalPixNumbers"),copySendWhatsapp:$("copySendWhatsappBtn"),jump:$("numberJump"),jumpBtn:$("jumpBtn"),prizeText:$("prizeText"),prizeInfo:$("prizeInfo"),drawInfo:$("drawInfo"),instagramInfo:$("instagramInfo"),beneficiaryPhoto:$("beneficiaryPhoto"),heroGoal:$("heroGoal"),unitPriceFact:$("unitPriceFact"),goalFact:$("goalFact"),totalNumbersFact:$("totalNumbersFact"),countAnnouncement:$("raffleCountAnnouncement"),rangeAnnouncement:$("raffleRangeAnnouncement"),potentialAnnouncement:$("potentialAnnouncement"),goalInfo:$("goalInfo"),unitPriceInfo:$("unitPriceInfo"),totalNumbersInfo:$("totalNumbersInfo"),numberRangeInfo:$("numberRangeInfo"),potentialInfo:$("potentialInfo"),prizeHighlightText:$("prizeHighlightText"),shareWhatsappBtn:$("shareWhatsappBtn")};
  const DDDS=new Set("11 12 13 14 15 16 17 18 19 21 22 24 27 28 31 32 33 34 35 37 38 41 42 43 44 45 46 47 48 49 51 53 54 55 61 62 63 64 65 66 67 68 69 71 73 74 75 77 79 81 82 83 84 85 86 87 88 89 91 92 93 94 95 96 97 98 99".split(" "));
  const digits=v=>String(v||"").replace(/\D/g,"");
  const totalNumbers=()=>Math.max(1,Number(state.raffleState?.total_numbers||cfg.fallbackTotalNumbers||1000));
  const unitPrice=()=>Math.max(1,Number(state.raffleState?.unit_price_cents||cfg.fallbackUnitPriceCents||1000));
  const goalCents=()=>Math.max(1,Number(state.raffleState?.goal_cents||cfg.fallbackGoalCents||1000000));
  const numberDigits=()=>String(totalNumbers()).length;
  const pad=n=>String(n).padStart(numberDigits(),"0");
  const money=c=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format((Number(c)||0)/100);
  const potentialCents=()=>totalNumbers()*unitPrice();
  function normalizeBrazilPhone(value,{requireMobile=false}={}){let d=digits(value);if(!d)return{ok:false,error:"Digite o telefone com DDD."};if(d.startsWith("00"))d=d.slice(2);if(d.startsWith("5555")&&(d.length===14||d.length===15))d=d.slice(2);if(d.startsWith("55")&&(d.length===12||d.length===13))d=d.slice(2);if(d.length!==10&&d.length!==11)return{ok:false,error:"Telefone inválido. Use DDD + número."};const ddd=d.slice(0,2),sub=d.slice(2);if(!DDDS.has(ddd))return{ok:false,error:`DDD ${ddd} inválido.`};if(d.length===11&&sub[0]!=="9")return{ok:false,error:"Celular inválido: depois do DDD, o número deve começar com 9."};if(d.length===10&&requireMobile)return{ok:false,error:"Para WhatsApp de celular, digite DDD + 9 dígitos."};if(d.length===10&&!/^[2-9]/.test(sub))return{ok:false,error:"Telefone fixo inválido."};return{ok:true,national:d,e164:`55${d}`}}
  function formatPhoneInput(value){const raw=String(value||"");let d=digits(raw);if(d.startsWith("5555")&&(d.length===14||d.length===15))d=d.slice(2);const explicit=/^\s*\+55\b/.test(raw)||(d.startsWith("55")&&d.length>11);if(explicit&&d.startsWith("55"))d=d.slice(2);d=d.slice(0,11);if(d.length<=2)return d;if(d.length<=6)return`(${d.slice(0,2)}) ${d.slice(2)}`;if(d.length<=10)return`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`;return`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`}
  function loadPending(){try{return JSON.parse(localStorage.getItem(PENDING_KEY)||"null")}catch{return null}}
  function savePending(v){state.pending=v;if(v)localStorage.setItem(PENDING_KEY,JSON.stringify(v));else localStorage.removeItem(PENDING_KEY)}
  function toast(msg,kind="normal"){el.toast.textContent=msg;el.toast.dataset.kind=kind;el.toast.classList.add("toast--show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("toast--show"),3300)}
  function setConnection(text,ok=false){el.badge.textContent=text;el.badge.classList.toggle("connection-badge--ok",ok)}
  function selectedMethod(){return document.querySelector('input[name="paymentMethod"]:checked')?.value||"infinitepay"}
  function showPaymentCard(kind,title,text,opt={}){el.paymentCard.className=`card payment-status-card payment-status-card--${kind||"warning"}`;el.paymentCard.classList.remove("hidden");el.paymentTitle.textContent=title;el.paymentText.textContent=text;el.continuePayment.classList.toggle("hidden",!opt.continuePayment);el.receiptLink.classList.toggle("hidden",!opt.receiptUrl);if(opt.receiptUrl)el.receiptLink.href=opt.receiptUrl}
  function setupStatic(){const prize=cfg.prizeText||"R$ 200 no Pix";el.prizeText.textContent=prize;el.prizeInfo.textContent=prize;if(el.prizeHighlightText)el.prizeHighlightText.textContent=prize.toUpperCase();el.drawInfo.textContent=cfg.drawAt?`${cfg.drawDateText||""} ${cfg.drawTimeText?`• ${cfg.drawTimeText}`:""}`:"A definir";if(cfg.instagramHandle&&cfg.instagramUrl){el.instagramInfo.classList.remove("hidden");el.instagramInfo.innerHTML=`Sorteio/atualizações: <a href="${cfg.instagramUrl}" target="_blank" rel="noopener">${cfg.instagramHandle}</a>`}if(cfg.beneficiaryPhoto)el.beneficiaryPhoto.src=cfg.beneficiaryPhoto}
  function renderCampaignConfig(){const total=totalNumbers(),unit=unitPrice(),goal=goalCents(),digitsCount=numberDigits(),range=`${String(1).padStart(digitsCount,"0")} a ${String(total).padStart(digitsCount,"0")}`;el.heroGoal.textContent=money(goal);el.goalFact.textContent=money(goal);el.unitPriceFact.textContent=money(unit);el.totalNumbersFact.textContent=total.toLocaleString("pt-BR");el.countAnnouncement.textContent=`🎟️ Rifa com ${total.toLocaleString("pt-BR")} números`;el.rangeAnnouncement.textContent=`Números disponíveis na faixa: ${range}`;el.potentialAnnouncement.textContent=`Arrecadação máxima com os números: ${money(potentialCents())}`;el.goalInfo.textContent=money(goal);el.unitPriceInfo.textContent=money(unit);el.totalNumbersInfo.textContent=total.toLocaleString("pt-BR");el.numberRangeInfo.textContent=range;el.potentialInfo.textContent=money(potentialCents());el.jump.maxLength=digitsCount;el.jump.placeholder=`Ex.: ${String(Math.min(total,Math.max(1,Math.ceil(total*.42)))).padStart(digitsCount,"0")}`;el.loading.textContent=`Carregando ${total.toLocaleString("pt-BR")} números…`}
  async function releaseExpired(){try{await db.rpc("junior_release_expired_pending")}catch(e){console.warn(e)}}
  async function loadAll(){setConnection("Sincronizando...");await releaseExpired();const[n,s]=await Promise.all([db.from("junior_raffle_numbers").select("number,status").order("number"),db.from("junior_raffle_public_state").select("sales_closed,draw_at,prize_text,instagram_handle,winner_number,drawn_at,total_numbers,unit_price_cents,goal_cents").eq("id",1).single()]);if(n.error||s.error){console.error(n.error||s.error);el.setupWarning.classList.remove("hidden");setConnection("Banco não instalado");return}state.raffleState=s.data;const total=totalNumbers();state.numbers=new Map(n.data.filter(r=>Number(r.number)<=total).map(r=>[Number(r.number),r.status]));for(const x of [...state.selected])if(x>total)state.selected.delete(x);renderCampaignConfig();el.loading.classList.add("hidden");el.grid.classList.remove("hidden");setConnection("Ao vivo",true);renderAll();subscribe()}
  function subscribe(){if(state.channel)db.removeChannel(state.channel);state.channel=db.channel("junior-public-live-v2").on("postgres_changes",{event:"*",schema:"public",table:"junior_raffle_numbers"},p=>{const n=Number((p.new||p.old).number);if(n<=totalNumbers()){if(p.eventType==="DELETE")state.numbers.delete(n);else if(p.new?.status)state.numbers.set(n,p.new.status);renderAll()}}).on("postgres_changes",{event:"*",schema:"public",table:"junior_raffle_public_state"},()=>loadAll()).subscribe()}
  function renderAll(){renderGrid();renderSelection();renderStats();renderWinner()}
  function renderGrid(){const total=totalNumbers(),frag=document.createDocumentFragment();for(let n=1;n<=total;n++){const status=state.numbers.get(n)||"available",b=document.createElement("button");b.type="button";b.id=`num-${n}`;b.className="number-btn";b.textContent=pad(n);b.dataset.number=n;if(status==="paid"){b.classList.add("number-btn--paid");b.disabled=true;b.title="Pago"}else if(status==="pending"){b.classList.add("number-btn--pending");b.disabled=true;b.title="Selecionado por outra pessoa"}else if(state.selected.has(n)){b.classList.add("number-btn--selected");b.title="Selecionado por você"}b.addEventListener("click",()=>toggleNumber(n));frag.appendChild(b)}el.grid.replaceChildren(frag)}
  function toggleNumber(n){if(state.numbers.get(n)!=="available")return;if(state.selected.has(n))state.selected.delete(n);else state.selected.add(n);renderGrid();renderSelection()}
  function renderSelection(){const nums=[...state.selected].sort((a,b)=>a-b),total=nums.length*unitPrice(),txt=nums.length?nums.map(pad).join(", "):"Nenhum";el.selectedNumbersMain.textContent=txt;el.selectedNumbers.textContent=txt;el.selectedTotalMain.textContent=money(total);el.selectedTotal.textContent=money(total);el.openCheckout.disabled=!nums.length;el.purchaseButton.textContent=`${selectedMethod()==="infinitepay"?"Continuar":"Registrar"} • ${money(total)}`}
  function renderStats(){let available=0,paid=0,pending=0;for(let n=1;n<=totalNumbers();n++){const s=state.numbers.get(n)||"available";if(s==="available")available++;if(s==="paid")paid++;if(s==="pending")pending++}el.available.textContent=available;el.paid.textContent=paid;el.pendingCount.textContent=pending;const pct=Math.min(100,(paid/totalNumbers())*100);el.progressBar.style.width=`${pct}%`;el.progressText.textContent=`${paid} de ${totalNumbers()} números pagos (${pct.toFixed(1).replace(".",",")}%).`}
  function renderWinner(){const w=Number(state.raffleState?.winner_number||0);el.winnerPublic.classList.toggle("hidden",!w);if(w)el.winnerPublicNumber.textContent=pad(w)}
  function openCheckout(){if(!state.selected.size)return;renderSelection();el.checkoutModal.classList.remove("hidden");el.checkoutModal.setAttribute("aria-hidden","false");setTimeout(()=>el.name.focus(),30)}
  function requestCloseCheckout(){el.cancelChoiceModal.classList.remove("hidden")}function closeCheckoutKeep(){el.cancelChoiceModal.classList.add("hidden")}function cancelChoice(){state.selected.clear();el.cancelChoiceModal.classList.add("hidden");el.checkoutModal.classList.add("hidden");renderAll()}
  function updateMethod(){const m=selectedMethod();el.methodInfiniteCard.classList.toggle("payment-method--active",m==="infinitepay");el.methodPersonalCard.classList.toggle("payment-method--active",m==="personal_pix");el.methodCashCard.classList.toggle("payment-method--active",m==="cash");el.cashPaymentFields.classList.toggle("hidden",m!=="cash");if(m==="infinitepay")el.paymentHelp.textContent=`Você será encaminhado ao checkout da InfinitePay ${cfg.infinitePay.displayHandle||"do Júnior"}.`;else if(m==="personal_pix")el.paymentHelp.textContent="Os números ficam pendentes até a confirmação manual do Pix.";else el.paymentHelp.textContent="Os números ficam pendentes até o administrador confirmar o dinheiro recebido.";renderSelection()}
  async function gateway(body){const r=await fetch(cfg.infinitePay.gatewayUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok||data.success===false)throw new Error(data.message||"Não foi possível concluir a operação.");return data}
  function validatedBuyer(){const name=el.name.value.trim();if(name.length<2)throw new Error("Digite um nome válido.");const p=normalizeBrazilPhone(el.phone.value,{requireMobile:true});if(!p.ok)throw new Error(p.error);return{name,whatsapp:p.national}}
  async function submitPurchase(ev){ev.preventDefault();try{const buyer=validatedBuyer(),numbers=[...state.selected].sort((a,b)=>a-b),method=selectedMethod();if(!numbers.length)throw new Error("Escolha pelo menos um número.");el.purchaseButton.disabled=true;el.purchaseButton.textContent="Processando…";if(method==="infinitepay"){if(!cfg.infinitePay.handle)throw new Error("InfinitePay ainda não configurada para esta rifa.");const data=await gateway({action:"create",...buyer,numbers,redirect_url:location.href.split("#")[0]});savePending({provider:"infinitepay",order_nsu:data.order_nsu,url:data.url,numbers,amount_cents:data.amount_cents});location.href=data.url;return}if(method==="personal_pix"){const data=await gateway({action:"create_personal_pix",...buyer,numbers});savePending({provider:"personal_pix",order_nsu:data.order_nsu,numbers:data.numbers,amount_cents:data.amount_cents,buyer_name:buyer.name});state.selected.clear();el.checkoutModal.classList.add("hidden");showPersonalPix(data);renderAll();return}const receivedBy=el.cashReceivedBy.value.trim(),rp=normalizeBrazilPhone(el.cashReceivedPhone.value,{requireMobile:false});if(receivedBy.length<2)throw new Error("Informe quem recebeu o dinheiro.");if(!rp.ok)throw new Error(rp.error);const data=await gateway({action:"create_cash_payment",...buyer,numbers,cash_received_by:receivedBy,cash_received_phone:rp.national});savePending({provider:"cash",order_nsu:data.order_nsu,numbers:data.numbers,amount_cents:data.amount_cents});state.selected.clear();el.checkoutModal.classList.add("hidden");showPaymentCard("warning","Pagamento em dinheiro pendente","Seus números foram registrados e aguardam a confirmação do administrador.");renderAll()}catch(e){toast(e.message||"Erro ao registrar pedido","error")}finally{el.purchaseButton.disabled=false;renderSelection()}}
  function showPersonalPix(order){const key=order.pix_key||cfg.personalPix.key,owner=order.pix_owner||cfg.personalPix.owner;el.personalPixKey.textContent=key||"A definir";el.personalPixOwner.textContent=owner||"A definir";el.personalPixAmount.textContent=money(order.amount_cents);el.personalPixNumbers.textContent=(order.numbers||[]).map(pad).join(", ");el.personalPixPanel.classList.remove("hidden");el.personalPixPanel.scrollIntoView({behavior:"smooth",block:"center"})}
  async function copyText(text){if(!text)return false;try{await navigator.clipboard.writeText(text);return true}catch{const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();const ok=document.execCommand("copy");ta.remove();return ok}}
  function shareRaffleWhatsapp(){try{const prize=cfg.prizeText||"R$ 200 no Pix",url=cfg.publicUrl||"https://luizemsaopaulo.github.io/RIFA_BENEFICENTE_CIRURGIA_JUNIOR/",unit=money(unitPrice()).replace(/\u00a0/g," ");const msg=["💚 Rifa Beneficente — Ajude o Júnior","",`🎁 Prêmio: ${prize}`,`🎟️ Cada número: ${unit}`,"","O Júnior está enfrentando uma hérnia de disco e tem sofrido com dores constantes e intensas. A rifa está sendo realizada para ajudar nos custos da cirurgia.","","Participe e compartilhe 🙏","",url].join("\n");window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}catch(e){toast(e.message||"Não foi possível abrir o WhatsApp","error")}}
  async function copyPixAndWhatsapp(){try{const pending=state.pending;if(!pending||pending.provider!=="personal_pix")throw new Error("Pedido Pix não encontrado.");const pix=el.personalPixKey.textContent.trim();if(!pix||pix==="A definir")throw new Error("A chave Pix ainda não foi configurada.");const copied=await copyText(pix);toast(copied?"Chave Pix copiada ✓":"Não foi possível copiar automaticamente.");try{await gateway({action:"personal_pix_contacted",order_nsu:pending.order_nsu})}catch(e){console.warn(e)}const organizer=normalizeBrazilPhone(cfg.organizerWhatsapp,{requireMobile:true});if(!organizer.ok)throw new Error("O WhatsApp do organizador ainda não foi configurado.");const msg=["Olá! Fiz/estou fazendo o Pix da rifa beneficente do Júnior.",`Nome: ${pending.buyer_name||el.name.value.trim()}`,`Números: ${(pending.numbers||[]).map(pad).join(", ")}`,`Valor: ${money(pending.amount_cents)}`].join("\n");window.open(`https://wa.me/${organizer.e164}?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}catch(e){toast(e.message||"Não foi possível abrir o WhatsApp","error")}}
  async function checkPending(){const p=state.pending;if(!p?.order_nsu)return;try{const{data,error}=await db.rpc("junior_payment_status",{p_order_nsu:p.order_nsu});if(error)throw error;if(!data?.found){savePending(null);return}if(data.payment_status==="paid"){showPaymentCard("success","Pagamento confirmado","Seus números estão pagos e participam do sorteio.",{receiptUrl:data.receipt_url});savePending(null);await loadAll();return}if(data.payment_status==="expired"||data.payment_status==="cancelled"){showPaymentCard("error","Pedido liberado","Esse pedido não está mais segurando os números.");savePending(null);await loadAll();return}if(p.provider==="infinitepay"&&p.url)showPaymentCard("warning","Pagamento pendente","O checkout ainda está pendente.",{continuePayment:true});if(p.provider==="personal_pix")showPersonalPix({pix_key:cfg.personalPix.key,pix_owner:cfg.personalPix.owner,amount_cents:p.amount_cents,numbers:p.numbers})}catch(e){console.warn(e)}}
  function jumpToNumber(){const n=Number(digits(el.jump.value));if(!Number.isInteger(n)||n<1||n>totalNumbers()){toast(`Digite um número de 1 a ${totalNumbers()}.`);return}const b=$(`num-${n}`);b?.scrollIntoView({behavior:"smooth",block:"center"});b?.classList.add("number-btn--flash");setTimeout(()=>b?.classList.remove("number-btn--flash"),1800)}
  el.phone.addEventListener("input",()=>{el.phone.value=formatPhoneInput(el.phone.value)});el.cashReceivedPhone.addEventListener("input",()=>{el.cashReceivedPhone.value=formatPhoneInput(el.cashReceivedPhone.value)});el.clear.addEventListener("click",()=>{state.selected.clear();renderAll()});el.openCheckout.addEventListener("click",openCheckout);el.checkoutClose.addEventListener("click",requestCloseCheckout);el.checkoutModal.querySelector(".modal__backdrop").addEventListener("click",requestCloseCheckout);el.keepCheckout.addEventListener("click",closeCheckoutKeep);el.confirmCancelCheckout.addEventListener("click",cancelChoice);document.querySelectorAll('input[name="paymentMethod"]').forEach(i=>i.addEventListener("change",updateMethod));el.form.addEventListener("submit",submitPurchase);el.copySendWhatsapp.addEventListener("click",copyPixAndWhatsapp);if(el.shareWhatsappBtn)el.shareWhatsappBtn.addEventListener("click",shareRaffleWhatsapp);el.continuePayment.addEventListener("click",()=>{if(state.pending?.url)location.href=state.pending.url});el.jumpBtn.addEventListener("click",jumpToNumber);el.jump.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();jumpToNumber()}});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!el.checkoutModal.classList.contains("hidden"))requestCloseCheckout()});
  setupStatic();updateMethod();loadAll();checkPending();setInterval(checkPending,12000);setInterval(releaseExpired,60000);
})();